-- MySQL Script generated by MySQL Workbench
-- Sat Nov 23 00:41:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Schema drawinggame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `drawinggame` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `drawinggame` ;

-- -----------------------------------------------------
-- Schema users
-- -----------------------------------------------------
CREATE TABLE users (
  user_id int(11) primary key not null auto_increment,
  username varchar(50) not null,
  password varchar(50) not null
);

-- -----------------------------------------------------
-- Table `drawinggame`.`words`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drawinggame`.`words` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `words` (`id`,`word`) VALUES (1,'apple');
INSERT INTO `words` (`id`,`word`) VALUES (2,'ball');
INSERT INTO `words` (`id`,`word`) VALUES (3,'cat');
INSERT INTO `words` (`id`,`word`) VALUES (4,'dog');
INSERT INTO `words` (`id`,`word`) VALUES (5,'fish');
INSERT INTO `words` (`id`,`word`) VALUES (6,'house');
INSERT INTO `words` (`id`,`word`) VALUES (7,'tree');
INSERT INTO `words` (`id`,`word`) VALUES (8,'star');
INSERT INTO `words` (`id`,`word`) VALUES (9,'sun');
INSERT INTO `words` (`id`,`word`) VALUES (10,'moon');
INSERT INTO `words` (`id`,`word`) VALUES (11,'hat');
INSERT INTO `words` (`id`,`word`) VALUES (12,'car');
INSERT INTO `words` (`id`,`word`) VALUES (13,'chair');
INSERT INTO `words` (`id`,`word`) VALUES (14,'boat');
INSERT INTO `words` (`id`,`word`) VALUES (15,'bird');
INSERT INTO `words` (`id`,`word`) VALUES (16,'key');
INSERT INTO `words` (`id`,`word`) VALUES (17,'book');
INSERT INTO `words` (`id`,`word`) VALUES (18,'flower');
INSERT INTO `words` (`id`,`word`) VALUES (19,'pencil');
INSERT INTO `words` (`id`,`word`) VALUES (20,'clock');
INSERT INTO `words` (`id`,`word`) VALUES (21,'pizza');
INSERT INTO `words` (`id`,`word`) VALUES (22,'banana');
INSERT INTO `words` (`id`,`word`) VALUES (23,'ice cream');
INSERT INTO `words` (`id`,`word`) VALUES (24,'cloud');
INSERT INTO `words` (`id`,`word`) VALUES (25,'heart');

SELECT * FROM words;